stages:
  - build
  - test
  - report
  - release
  - deploy
  - cleanup

variables:
  ISOLATION: "buildpipeline${CI_PIPELINE_ID}${CI_PROJECT_NAME}"
  STACK_PHP_IMAGE: "${PHP_IMAGE_NAME}:${CI_BUILD_REF}"
  REGISTRY_PHP_IMAGE: "${PHP_IMAGE_NAME}:${CI_BUILD_REF_NAME}"
  FLAVOUR: ""

# ----------------------------------------------------------
# before/after scripts, these will be used in every job within the job-scope
# ----------------------------------------------------------
before_script:
  # set docker-compose isolation
  - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}
  - pwd
  - docker version
  - docker-compose version
  - echo ${ISOLATION}
  - echo $(git describe --always --dirty --tags)
  - ([[ $FLAVOUR ]] && echo "build flavour is $FLAVOUR" || echo "build flavour is default/undefinied")
  # run all commands from test environment

after_script:
  # set docker-compose isolation
  - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}
  # run all commands from test environment
  - make clean

# ----------------------------------------------------------
# TEMPLATES
# ----------------------------------------------------------
# templates for flavour definitions used in jobs
.build_flavour_debian_tmpl: &build_flavour_debian_tmpl_ref
  variables:
    FLAVOUR: "-debian"
# ----------------------------------------------------------
# templates which can be used in jobs with different flavours
.codeception_tmpl: &codeception_tmpl_ref
  stage: test
  script:
    - make test
  except:
    - coverage
  artifacts:
    name: ${CI_PROJECT_PATH}-p${CI_PIPELINE_ID}-codeception
    when: always
    expire_in: 4 weeks
    paths:
      - tests/_log


.lint_tmpl: &lint_tmpl_ref
  stage: test
  script:
    - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}
    - make help
    - make lint
    - make lint-composer
  artifacts:
    name: ${CI_PROJECT_PATH}-p${CI_PIPELINE_ID}-lint
    when: always
    expire_in: 4 weeks
    paths:
      - tests/_log


.coverage_tmpl: &coverage_tmpl_ref
  stage: test
  script:
    - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}
    - export PHP_ENABLE_XDEBUG=1
    - make test-coverage
  only:
    - coverage
  artifacts:
    name: ${CI_PROJECT_PATH}-p${CI_PIPELINE_ID}-coverage
    when: always
    expire_in: 4 weeks
    paths:
      - tests/_log


.release_tmpl: &release_tmpl_ref
  stage: release
  environment:
    name: image
  script:
    - docker login --username ${REGISTRY_USER} --password ${REGISTRY_PASS} ${REGISTRY_HOST}
    - make version build
    - docker tag ${STACK_PHP_IMAGE}${FLAVOUR} ${REGISTRY_PHP_IMAGE}${FLAVOUR}
    - docker push ${REGISTRY_PHP_IMAGE}${FLAVOUR}
  only:
    - latest
    - experimental
    - tags


# ----------------------------------------------------------
# job definitions, they should use the defined job and flavour templates
# ----------------------------------------------------------
codeception-debian:
  <<: *build_flavour_debian_tmpl_ref
  <<: *codeception_tmpl_ref

# ----------------------------------------------------------
coverage-debian:
  <<: *build_flavour_debian_tmpl_ref
  <<: *coverage_tmpl_ref

# ----------------------------------------------------------
lint-debian:
  <<: *build_flavour_debian_tmpl_ref
  <<: *lint_tmpl_ref

# ----------------------------------------------------------
release-debian:
  <<: *build_flavour_debian_tmpl_ref
  <<: *release_tmpl_ref

# ----------------------------------------------------------
deploy:staging:
  stage: deploy
  environment: staging
  allow_failure: true
  script:
    - echo "Auto-deployment trigger not implemented."
    - exit 1
  only:
    - latest
