sudo: required

language: php

services:
  - docker

before_install:
  - export APP_VERSION=$(git describe --always --dirty)
  - export STACK_PHP_IMAGE=${TRAVIS_REPO_SLUG}:${APP_VERSION}
  - export STACK_PHP_IMAGE_LATEST=${TRAVIS_REPO_SLUG}:latest
  - cp .env-dist .env
  - mkdir -p _host-volumes/tests-log

script:
  - make test
