version: '3.2'
services:
  php:
    environment:
      # TODO: use data migrations for tests
      - APP_MIGRATION_LOOKUP=@app/migrations

      - DATABASE_DSN_BASE=pgsql:host=postgres
      - DATABASE_DSN_DB=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=mysecretpassword
      - DATABASE_TABLE_PREFIX=app_
  postgres:
    image: postgres:9.2
