# Development stack overrides
#
# Variables are populated with values from `.env`
#
version: '3.2'
services:
  php:
    build:
      context: ..
      # FLAVOUR can be undefinied OR -debian
      # undefined == alpine base image
      # -debian   == debian base image
      dockerfile: Dockerfile${FLAVOUR}
    ports:
      - 80
    depends_on:
      - db
      - redis
    environment:
      - DB_ENV_MYSQL_ROOT_PASSWORD=secret
      # For host-volume development (permissions)
      # For composer usage in container
      - GITHUB_API_TOKEN
      - ENV_LOCAL_FILE=config/local.env
      - APP_MAILER_USE_FILE_TRANSPORT=1
      - APP_ADMIN_PASSWORD=admin1
      - APP_ADMIN_EMAIL=admin@local.develop
      - APP_ASSET_FORCE_PUBLISH=1
      - APP_PAGES_TITLE_PREFIX='[DEV] '
      - PHP_ENABLE_XDEBUG
    volumes:
      # Re-use local composer cache via host-volume
      - type: bind
        source: $HOME/.composer-docker/cache
        target: /root/.composer/cache
        consistency: delegated
      - type: bind
        source: ../src
        target: /app/src
        consistency: cached
      - type: bind
        source: ../vendor-dev
        target: /app/vendor
        consistency: delegated
      - type: bind
        source: ../_host-volumes/runtime/mysql
        target: /app/runtime/mysql
        consistency: delegated

  db:
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306'
